SRCFILE1 = WifiCalibration.tex
SRCFILE2 = WiFi_Calibration.tex
LATEXCOM = xelatex
OUTFILE = *.gz *.pdf *.log *.aux *.out *.toc *~ *.gz*
CLEANCOM = rm -rf

all:
	${LATEXCOM} ${SRCFILE1}
	${LATEXCOM} ${SRCFILE1}

	${LATEXCOM} ${SRCFILE2}
	${LATEXCOM} ${SRCFILE2}

clean:
	${CLEANCOM} ${OUTFILE}	
