SRCFILE = WifiCalibration.tex
LATEXCOM = xelatex
OUTFILE = *.gz *.pdf *.log *.aux *.out *.toc *~
CLEANCOM = rm -rf

all:
	${LATEXCOM} ${SRCFILE}
	${LATEXCOM} ${SRCFILE}

clean:
	${CLEANCOM} ${OUTFILE}	
